language: node_js

node_js:
  - 'node'
  - 'lts/*'

services:
  - xvfb

script:
  - npm run test:api

before_install:
  - curl -sL https://firebase.tools | bash
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0

before_script:
  - npm rebuild grpc --build-from-source

notifications:
  email:
    on_failure: change

cache:
  directories:
    - node_modules

deploy:
  - provider: pages
    local_dir: build
    target_branch: gh-pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    on:
      branch: master
  - provider: firebase
    project: mediumus-69aeb
    token:
      secure: $FIREBASE_TOKEN
    on:
      branch: master
  - provider: firebase
    project: mediumus-dev
    token:
      secure: $FIREBASE_TOKEN
    on:
      branch: api-dev
