language: node_js

node_js:
  - 'node'

services:
  - xvfb

script:
  - npm run build

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0

notifications:
  email:
    on_failure: change

cache:
  directories:
    - node_modules

deploy:
  - provider: pages
    local_dir: build
    target_branch: gh-pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    on:
      branch: master

os: linux
